### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by trdavidson** [mapbox/mapbox-ios-sdk-offline#1]
After running the Pod install, and opening the Workspace, the code does not compile. 'RMFoundation.h' not found, and 'Could not compile Objective C module Mapbox_iOS_SDK' are the error messages. This is out of the box with no modifications on my end.

EDIT:
Following suggestions https://github.com/mapbox/mapbox-ios-sdk/issues/632 I was able to make this compile setting all .h files to public manually. However, after running the example app and moving around a little, the app will freeze and crash due to memory pressure.

**Comment by friedbunny** [comment]
CocoaPods issue fixed in https://github.com/mapbox/mapbox-ios-sdk/commit/3bb61e8a7bf91090c5c195fa1589f62499b20805.
